build: off

# branches to build
branches:
  only:
    - master
    - appveyor

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - where python
  - python -m conda install modtox -y


test_script:
  - "%PYTHON%\\python.exe -m pytest"

after_test:
  - "%PYTHON%\\python.exe  setup.py bdist_wheel"

artifacts:
  - path: dist\*

notifications:
  - provider: Email
    to:
      - dsoler@nostrumbiodiscovery.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
