build: off

# branches to build
branches:
  only:
    - master
    - appveyor

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"
      CONDA_NPY: "1.10"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - where python
  - python -m conda install -c rdkit -c josan_bcn -c nostrumbiodiscovery -c ambermd -c conda-forge mdtraj biopython seaborn scipy==1.1.0 mordred nltk requests matplotlib  -y
  - python -m pip install sklearn prody umap-learn


test_script:
  - "%PYTHON%\\python.exe -m pytest"

after_test:
  - "%PYTHON%\\python.exe  setup.py bdist_wheel"

artifacts:
  - path: dist\*

notifications:
  - provider: Email
    to:
      - dsoler@nostrumbiodiscovery.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
