build: off

# branches to build
branches:
  only:
    - master
    - appveyor

environment:
  matrix:
#    - PYTHON: "C:\\Python27"     # comment out due to tensorflow version
#    - PYTHON: "C:\\Python27-x64" # comment out due to tensorflow version
    - PYTHON: "C:\\Python35-x64"
#    - PYTHON: "C:\\Python36-x32"
    - PYTHON: "C:\\Python36-x64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - CPPTRAJHOME=''
  - "%PYTHON%\\python.exe -m pip install modtox"


test_script:
  - "%PYTHON%\\python.exe -m pytest"

after_test:
  - "%PYTHON%\\python.exe  setup.py bdist_wheel"

artifacts:
  - path: dist\*

notifications:
  - provider: Email
    to:
      - dsoler@nostrumbiodiscovery.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
